version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: consecutive-items-subset-arrangement:1.0
    container_name: consecutive-items-subset-arrangement
    command: python3 main.py
    environment:
      TZ: America/Indiana/Indianapolis
      PYTHONUNBUFFERED: 1
      LOG_LEVEL: ${LOG_LEVEL}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      NUMBER_OF_PROCESSES: ${NUMBER_OF_PROCESSES}
    volumes:
      - ./plan.csv:/app/plan.csv
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "10"
          memory: 50GB
        reservations:
          cpus: "1"
          memory: 2GB
  db:
    image: postgres
    restart: unless-stopped
    container_name: cisa-pg-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: "exit 0"
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
